export const GET_ERRORS = 'GET_ERRORS';
export const SET_TOKEN = 'SET_TOKEN';
export const UNSET_TOKEN = 'UNSET_TOKEN';
export const SET_USER = 'SET_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const REGISTER_AUTHENTICATED = 'REGISTER_AUTHENTICATED';


export const GET_SEARCH_DATA = 'GET_SEARCH_DATA';
export const REMOVE_SEARCH_DATA = 'REMOVE_SEARCH_DATA';
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';
export const SAVE_SEARCH_CRITERIA = "SAVE_SEARCH_CRITERIA";
export const SAVE_ADVANCE_SEARCH_CRITERIA = "SAVE_ADVACE_SEARCH_CRITERIA"

export const SET_COMPANY_INFO = "SET_COMPANY_INFO";
export const UNSET_COMPANY_INFO = "UNSET_COMPANY_INFO";

export const SET_PAGE_INFO = "SET_PAGE_INFO";
export const SET_PAGE_REAL_INFO = "SET_PAGE_REAL_INFO";
export const UNSET_PAGE_INFO = "UNSET_PAGE_INFO";

export const INITIAL_REQUEST = "INITIAL_REQUEST";
export const GET_META_DATA = "GET_META_DATA";

export const GET_BUSINESS_DATA = "GET_BUSINESS_DATA";
export const SET_SELECTED_SECTOR = "SET_SELECTED_SECTOR";
export const SET_SELECTED_COMPANIES = "SET_SELECTED_COMPANIES";

export const SET_TAB_STATUS = "SET_TAB_STATUS";
export const GET_FUNDING_ROUND_DATA = "GET_FUNDING_ROUND_DATA";

export const DELETE_FEED_CARDS = "DELETE_FEED_CARDS";
export const REMOVED_BOOKMARKS = "REMOVED_BOOKMARKS";



